language: node_js

node_js:
  - "6.10.1"

sudo: required
before_script:
  - npm install -g gulp
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
  - npm install
  - gulp
  - npm run coveralls
