export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';

export const CREATE_GROUP = 'CREATE_GROUP';

export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const ADD_USER_GROUPS = 'ADD_USER_GROUPS';

export const POST_MESSAGE = 'POST_MESSAGE';

export const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';

export const SET_CURRENT_GROUP_ID = 'SET_CURRENT_GROUP_ID';

export const SET_CURRENT_MESSAGES = 'SET_CURRENT_MESSAGES';

export const SET_CURRENT_MEMBERS = 'SET_CURRENT_MEMBERS';
