export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';

export const ADD_USER_DETAILS_ERROR = 'ADD_USER_DETAILS_ERROR';

export const CREATE_GROUP = 'CREATE_GROUP';

export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const ADD_USER_GROUPS = 'ADD_USER_GROUPS';

export const ADD_USER_GROUPS_ERROR = 'ADD_USER_GROUPS_ERROR';

export const POST_MESSAGE = 'POST_MESSAGE';

export const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';

export const POST_MESSAGE_TO_CURRENT_GROUP = 'POST_MESSAGE_TO_CURRENT_GROUP';

export const CLEAR_SEARCH_USER_STATUS = 'CLEAR_SEARCH_USER_STATUS';

export const SET_USERS = 'SET_USERS';

export const SET_CURRENT_MESSAGES = 'SET_CURRENT_MESSAGES';

export const SET_CURRENT_MESSAGES_ERROR = 'SET_CURRENT_MESSAGES_ERROR';

export const SET_CURRENT_MEMBERS = 'SET_CURRENT_MEMBERS';

export const ADD_NEW_MEMBER = 'ADD_NEW_MEMBER';

export const ADD_NEW_MEMBER_ERROR = 'ADD_NEW_MEMBER_ERROR';

export const GET_MY_MESSAGES = 'GET_MY_MESSAGES';

export const GET_ARCHIVED_MESSAGES = 'GET_ARCHIVED_MESSAGES';

export const RESET_MAIL_SUCCESS = 'RESET_MAIL_SUCCESS';

export const RESET_MAIL_ERROR = 'RESET_MAIL_ERROR';

export const SEARCH_USER = 'SEARCH_USER';

export const GET_USERS = 'GET_USERS';

export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';

export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';

export const GOOGLE_AUTH_ERROR = 'GOOGLE_AUTH_ERROR';

export const MARK_MESSAGE_AS_SEEN = 'MARK_MESSAGE_AS_SEEN';

export const MARK_MESSAGE_AS_SEEN_ERROR = 'MARK_MESSAGE_AS_SEEN_ERROR';

export const GET_ARCHIVED_MESSAGE = 'GET_ARCHIVED_MESSAGE';

export const GET_ARCHIVED_MESSAGE_ERROR = 'GET_ARCHIVED_MESSAGE_ERROR';

export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export const CLEAR_NOTIFICATION_ERROR = 'CLEAR_NOTIFICATION_ERROR';
